/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.condominiovalhalla;

import java.awt.Color;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.io.BufferedWriter;
/**
 *
 * @author dzuniga
 */
public class agregar extends javax.swing.JFrame {

    /**
     * Creates new form agregar
     */
    public agregar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_filial = new javax.swing.JTextField();
        txt_codigo = new javax.swing.JTextField();
        txt_placa = new javax.swing.JTextField();
        sw_estado = new javax.swing.JToggleButton();
        btn_guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agregar");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                abrirMain(evt);
            }
        });

        jLabel1.setText("Filial:");

        jLabel2.setText("Código:");

        jLabel3.setText("Placa:");

        jLabel4.setText("Estado");

        txt_filial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_filialActionPerformed(evt);
            }
        });

        sw_estado.setBackground(new java.awt.Color(255, 255, 51));
        sw_estado.setText("Inactivo");
        sw_estado.setToolTipText("");
        sw_estado.setBorderPainted(false);
        sw_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sw_estadoActionPerformed(evt);
            }
        });

        btn_guardar.setText("Guardar Registro");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_filial)
                                    .addComponent(txt_codigo)
                                    .addComponent(txt_placa, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(sw_estado))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btn_guardar)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_filial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sw_estado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(btn_guardar)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirMain(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_abrirMain
 
    }//GEN-LAST:event_abrirMain

    private void sw_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sw_estadoActionPerformed
        if (sw_estado.isSelected()){
            sw_estado.setText("Activo");
            sw_estado.setBackground(Color.green);
            
        }    // TODO add your handling code here:
        else{
            sw_estado.setText("Inactivo");
            sw_estado.setBackground(Color.YELLOW);
            
        }
    }//GEN-LAST:event_sw_estadoActionPerformed

    private void txt_filialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_filialActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_txt_filialActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        String filial = txt_filial.getText();
        String codigo = txt_codigo.getText();
        String placa = txt_placa.getText();
        String estado = sw_estado.getText();
        
        String linea = String.format("%-" + 15 + "s | %-" + 10 + "s | %-" + 8 + "s | %-" + 8 + "s", //el %-NUMs sirve para delimitar los espacios que van en esos campos
                                     filial, codigo, placa, estado);
        
        String registros = "registros.txt";
        if ("".equals(filial) || "".equals(codigo) || "".equals(placa) || "".equals(estado)){
                JOptionPane.showMessageDialog(null, "FALTAN DATOS POR LLENAR");
         
        }
        else{ 
            try{
            
                File txt = new File(registros);
                System.out.println("Ruta completa del archivo: " + txt.getAbsolutePath());
                FileWriter fw = new FileWriter(txt, true);
                BufferedWriter bw = new BufferedWriter(fw);
                bw.newLine();
                bw.write(linea);           
                bw.close();
                JOptionPane.showMessageDialog(null, "DATOS REGISTRADOS CON ÉXITO");
                Frame vtn_main = new Frame();
                vtn_main.setVisible(true);
                setVisible(false);

            }catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Ha fallado el registro");
            }
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToggleButton sw_estado;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_filial;
    private javax.swing.JTextField txt_placa;
    // End of variables declaration//GEN-END:variables
}
